version: '3.8'

services:
  calculator:
    build:
      context: .
      dockerfile: calculator/Dockerfile
    container_name: calculator
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - kafka-net

  rest:
    build:
      context: .
      dockerfile: rest/Dockerfile
    container_name: rest
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8080:8080"
    networks:
      - kafka-net

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - kafka-net

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge


